name: openjmu
description: A JMU Flutter application.

version: 0.9.0+142

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  badges: 1.1.0
  connectivity: ^0.4.6+2
  cookie_jar: 1.0.1
  crypto: any
  dartx: ^0.2.0
  device_info: ^0.4.1+4
  dio: 2.1.16
  event_bus: 1.1.0
  extended_image: ^0.6.9
  extended_list: ^0.1.3
  extended_tabs: ^0.2.2
  extended_text: ^0.7.0
  extended_text_field: ^0.4.8
  flutter_icons: ^1.0.0+1
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: "9c7ac0da8f01ceb40430da58397bdb31968ca5b1"
  flutter_local_notifications: ^0.9.1+3
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git
  flutter_platform_widgets: ^0.31.0
  flutter_qr_reader: 1.0.3
  flutter_screenutil: ^0.7.0
  flutter_svg: ^0.15.0
  flutter_webview_plugin: ^0.3.10
  hive: 1.3.0
  hive_flutter: ^0.3.0
  html: ^0.14.0+3
  image: any
  image_editor: ^0.1.4
  image_downloader: ^0.19.1
  image_gallery_saver: 1.2.2
  image_picker: 0.6.2+3
  intl: any
  isolate: ^2.0.2
  launch_review: 2.0.0
  like_button: ^0.1.9
  multi_image_picker: 4.6.0
  oktoast: 2.3.0
  open_file: 3.0.1
  ota_update: 2.0.2
  package_info: ^0.4.0+13
  path_provider: 1.3.0
  permission_handler: 4.1.0
  provider: 4.0.1
  pull_to_refresh_notification: ^0.3.3
  qr_flutter: 3.1.0
  quick_actions: ^0.4.0+1
  shared_preferences: ^0.5.6
  url_launcher: 5.4.1
  uuid: 2.0.4

dev_dependencies:
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter
  ff_annotation_route: ^1.1.4
  hive_generator: ^0.7.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/emotionIcons/
    - assets/icons/
    - assets/icons/addButton/
    - assets/icons/appCenter/
    - assets/icons/bottomNavigation/
    - assets/icons/gender/
    - assets/icons/postActions/
    - assets/icons/settings/
    - images/
    - images/placeholder/
  fonts:
    - family: chocolate
      fonts:
        - asset: assets/fonts/chocolate.ttf
