name: OpenJMU
description: A JMU Flutter application.

version: 0.3.13+35

environment:
    sdk: ">=2.1.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    badges: any
    cached_network_image: any
    cookie_jar: any
#    connectivity: ^0.4.3
    crypto: ^2.0.6
    dio: any
    dragablegridview_flutter: any
    event_bus: ^1.1.0
    extended_image: any
    extended_tabs: any
    extended_text: any
    extended_text_field: any
    image: ^2.0.7
    image_crop: ^0.2.0
    image_downloader: ^0.15.2
    image_picker: ^0.6.0+2
    fluttertoast: any
    flutter_cache_manager: any
#    flutter_calendar_carousel: ^1.3.16
#    flutter_colorpicker: ^0.2.3
    flutter_local_notifications: any
    flutter_icons: any
    flutter_native_image:
        git: https://github.com/btastic/flutter_native_image
    flutter_platform_widgets: any
    flutter_webview_plugin: any
    flutter_svg: ^0.12.4
    multi_image_picker: any
    ota_update: any
    package_info: any
    shared_preferences: any
    uuid: any

dev_dependencies:
    flutter_test:
        sdk: flutter


flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/emotionIcons/
        - assets/icons/
        - assets/icons/webApps/
        - images/
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700