name: OpenJMU
description: A JMU Flutter application.

version: 0.5.3+84

environment:
    sdk: ">=2.5.0 <3.0.0"
    flutter: 1.9.1+hotfix.4

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    badges: 1.1.0
    cached_network_image: 1.1.1
    connectivity: 0.4.4
    cookie_jar: 1.0.1
    crypto: 2.1.2
    dio: 2.1.16
    dragablegridview_flutter: 0.2.5
    event_bus: 1.1.0
    extended_image: 0.5.7
    extended_tabs: 0.2.2
    extended_text: 0.6.6
    extended_text_field: 0.4.4
    fluttertoast: 3.1.3
    flutter_cache_manager: 1.1.1
    flutter_downloader: 1.2.1
    flutter_icons: 0.2.5
    flutter_inappbrowser: 1.2.1
    flutter_native_image:
        git: https://github.com/btastic/flutter_native_image.git
    flutter_platform_widgets: 0.12.0
    flutter_qr_reader: 1.0.2
    flutter_screenutil: 0.6.0
    flutter_svg: 0.14.1
    flutter_webview_plugin: 0.3.8
    html: 0.14.0+2
    image: any
    image_crop: 0.3.1
    image_downloader: 0.18.1
    image_gallery_saver: 1.2.1
    image_picker: 0.6.1+1
    intl: 0.15.8
    like_button: 0.1.9
    multi_image_picker: 4.5.3
    oktoast: 2.2.0
    package_info: 0.4.0+6
    permission_handler: 3.2.2
    pull_to_refresh_notification: 0.3.2
    qr_flutter: 3.0.1
    quick_actions: 0.3.2+2
    shared_preferences: 0.5.3+4
#    sqflite: 1.1.6+3
    url_launcher: 5.1.2
    uuid: 2.0.2
    webview_flutter: 0.3.14

dev_dependencies:
    flutter_test:
        sdk: flutter


flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/emotionIcons/
        - assets/icons/
        - assets/icons/appCenter/
        - assets/icons/bottomNavigation/
        - assets/icons/gender/
        - assets/icons/postActions/
        - images/
    fonts:
        - family: chocolate
          fonts:
              - asset: assets/fonts/chocolate.ttf
