name: OpenJMU
description: A JMU Flutter application.

version: 0.3.15+37

environment:
    sdk: ">=2.1.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    badges: ^0.0.6
    cached_network_image: ^0.8.0
    cookie_jar: ^1.0.0
    crypto: ^2.0.6
    dio: ^2.1.3
    dragablegridview_flutter: ^0.2.0
    event_bus: ^1.1.0
    extended_image: any
    extended_tabs: any
    extended_text: any
    extended_text_field: any
    image: ^2.0.7
    image_crop: ^0.2.0
    image_downloader: ^0.15.2
    image_picker: ^0.6.0+2
    fluttertoast: any
    flutter_cache_manager: ^0.3.2
    flutter_local_notifications: ^0.7.0
    flutter_icons: any
    flutter_native_image:
        git: https://github.com/btastic/flutter_native_image
    flutter_platform_widgets: ^0.9.6
    flutter_webview_plugin: ^0.3.5
    flutter_svg: ^0.12.4
    multi_image_picker: ^4.2.1
    ota_update: any
    package_info: any
    shared_preferences: any
    uuid: ^2.0.1

dev_dependencies:
    flutter_test:
        sdk: flutter


flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/emotionIcons/
        - assets/icons/
        - assets/homeSplash/
        - images/
    fonts:
        - family: chocolate
          fonts:
              - asset: assets/fonts/chocolate.ttf
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700