name: OpenJMU
description: A JMU Flutter application.

version: 0.7.1+122

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  badges: 1.1.0
  connectivity: 0.4.6
  cookie_jar: 1.0.1
  crypto: any
  device_info: 0.4.1+3
  dio: 2.1.16
  event_bus: 1.1.0
  extended_image: 0.6.7
  extended_image_library: 0.1.8
  extended_list: 0.1.3
  extended_tabs: 0.2.2
  extended_text: 0.6.6
  extended_text_field: 0.4.4
  extended_text_library: 0.4.9
  fluttertoast: 3.1.3
  flutter_downloader: 1.2.2
  flutter_icons: ^1.0.0+1
  flutter_inappbrowser:
    git: https://github.com/AlexVincent525/flutter_inappbrowser.git
  flutter_local_notifications: ^0.8.4+3
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git
  flutter_platform_widgets: 0.20.2
  flutter_qr_reader: 1.0.3
  flutter_screenutil: ^0.7.0
  flutter_svg: ^0.15.0
  flutter_webview_plugin: ^0.3.10
  hive: 1.1.1
  hive_flutter: ^0.2.1
  html: ^0.14.0+3
  image: any
  image_editor: ^0.1.4
  image_downloader: ^0.19.1
  image_gallery_saver: 1.2.2
  image_picker: 0.6.2+2
  intl: any
  isolate: 2.0.2
  like_button: ^0.1.9
  multi_image_picker: 4.5.9
  oktoast: 2.2.1
  open_appstore: ^1.0.2
  package_info: 0.4.0+12
  permission_handler: 4.0.0
  provider: 3.2.0
  pull_to_refresh_notification: ^0.3.3
  qr_flutter: 3.1.0
  quick_actions: ^0.4.0
  shared_preferences: 0.5.4+8
  url_launcher: 5.2.7
  uuid: 2.0.4
  webview_flutter: ^0.3.17

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  ff_annotation_route: ^1.1.1
  hive_generator: ^0.5.2


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/emotionIcons/
    - assets/icons/
    - assets/icons/addButton/
    - assets/icons/appCenter/
    - assets/icons/bottomNavigation/
    - assets/icons/gender/
    - assets/icons/postActions/
    - images/
    - images/placeholder/
  fonts:
    - family: chocolate
      fonts:
        - asset: assets/fonts/chocolate.ttf
