name: OpenJMU
description: A JMU Flutter application.

version: 0.3.21+53

environment:
    sdk: ">=2.2.2 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    badges: 0.0.6
    cached_network_image: 0.8.0
    connectivity: ^0.4.3+1
    cookie_jar: ^1.0.0
    crypto: ^2.0.6
    dio: ^2.1.5
    dragablegridview_flutter: 0.2.0
    event_bus: 1.1.0
    extended_image: ^0.3.6
    extended_tabs: ^0.1.6
    extended_text: ^0.5.0
    extended_text_field: ^0.3.0
    fluttertoast: any
    flutter_cache_manager: 0.3.2
    flutter_downloader: 1.1.7
    flutter_icons: any
    flutter_local_notifications: ^0.7.1+1
    flutter_native_image:
        git: https://github.com/btastic/flutter_native_image/
    flutter_platform_widgets: ^0.9.6
    flutter_svg: ^0.12.4+1
    flutter_webview_plugin: ^0.3.5
    image_crop: ^0.2.1
    image_downloader: ^0.15.2
    image_picker: ^0.6.0+8
    multi_image_picker: ^4.3.3
    oktoast: ^2.1.7
    package_info: ^0.4.0+3
    permission_handler: ^3.1.0
    quick_actions: ^0.3.0+1
    shared_preferences: ^0.5.2+1
    uuid: ^2.0.1

dev_dependencies:
    flutter_test:
        sdk: flutter


flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/emotionIcons/
        - assets/icons/
        - assets/homeSplash/
        - images/
    fonts:
        - family: chocolate
          fonts:
              - asset: assets/fonts/chocolate.ttf
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700